title: The edge of random
email: eyjhbb@gmail.com
description: >- 
  Blog by eyJhb where I will try to post various
  random stuff, that I have found or done over time.
  Some of this you might find interesting, other not
  so much...
baseurl: "" 
url: "https://eyjhb.dk" 

# google analytics
google_analytics: UA-128656614-1

# social
twitter_username: eyJhb
github_username: eyJhb
rss: rss

# show excerpts on homepage
show_excerpts: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  

