baseURL = 'https://example.org/'
languageCode = 'en-gb'
title = 'The edge of random'
theme = 'hugo-bearblog'

# disableKinds = ["taxonomy"]
# ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/blog/:slug/"
  tags = "/blog/:slug"
